"""Add pets table

Revision ID: 10a926e9e098
Revises: b7cc2990ddc6
Create Date: 2025-01-31 10:57:59.729822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a926e9e098'
down_revision: Union[str, None] = 'b7cc2990ddc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', 'OTHER', name='species'), nullable=False),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='sex'), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('microchip_number', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microchip_number')
    )
    op.create_index(op.f('ix_pets_id'), 'pets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pets_id'), table_name='pets')
    op.drop_table('pets')
    # ### end Alembic commands ###
