"""Add questionnaire responses table

Revision ID: 1acfa82e23d7
Revises: 10a926e9e098
Create Date: 2025-01-31 11:57:40.848698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acfa82e23d7'
down_revision: Union[str, None] = '10a926e9e098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_responses',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_type', sa.Enum('GENERAL_CHECKUP', 'VACCINATION', 'SPECIFIC_CONCERN', 'EMERGENCY', name='questionnairetype'), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_responses_id'), 'questionnaire_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaire_responses_id'), table_name='questionnaire_responses')
    op.drop_table('questionnaire_responses')
    # ### end Alembic commands ###
